### PR TITLE
Added a button press (left/E) to set the name back to None and allow …

### PR DESCRIPTION
**Pull request by MikeS159**
…users to change their name again without having to re-flash the device.

Needs testing on a real badge. Simulator won't allow name changes and I am having trouble getting apps installed via USB.

### CODE REVIEW

**Comment by jake-walker** [comment]
Hi, thanks for your pull request! As it takes so long to type a name in, I'd like to make it a little harder to wipe the name out, perhaps a confirmation message or something? I'm not sure there's anything built-in that lets us do that at the moment. There's also a problem where it doesn't re-prompt for a name unless the app is killed and reopened, so I'll have a look into that.

**Comment by MikeS159** [comment]
Worked out how to flash apps over USB at last. Just tested that it works properly.
I think a confirmation is a good idea. I'll look at how to do that.

**Comment by MikeS159** [comment]
Done, confirmation tested on my badge. Also moved text so it can be seen properly

**Comment by jake-walker** [comment]
Looks great now, thanks!

**Pull request merged**
